on:
  issues:
    types: [ opened, labeled ]
name: Issue
jobs:
  issueHandler:
    name: Issue Handler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Issue Handler
      uses: jat001/Scoop-GithubActions@main-win
      if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
      env:
        GITH_USER: Jat
        GITH_EMAIL: jat@sinosky.org
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHOVEL: '1'
        SCOOP_BRANCH: 'NEW'
