on:
  pull_request:
    types: [ opened ]
name: Pull Request
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull Request Validator
      uses: jat001/Scoop-GithubActions@main-win
      env:
        GITH_USER: Jat
        GITH_EMAIL: jat@sinosky.org
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHOVEL: '1'
        SCOOP_BRANCH: 'NEW'
