on:
  pull_request:
    types: [ opened ]
name: Pull Request
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull Request Validator
      uses: Ash258/Scoop-GithubActions@stable-win
      env:
        GITH_EMAIL: jat@sinosky.org
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
